### ISSUE TITLE
RedHat/CentOS 6 support ?

### ISSUE THREAD

**Issue by linuxdan** [benformosa/puppet-linux_disable_ipv6#1]
Documentation says 
> Currently, only Red Hat Enterprise Linux 6 and 7 are supported.

but the only case in the case statement is for 7

**Comment by linuxdan** [comment]
Is this something you would want to add, considering the nearness of the EOL date ?

If so, I'd like to volunteer 😁

**Comment by benformosa** [comment]
Closing as RHEL 6 is now EOL. I've removed the references to RHEL 6 in the doco.
I would be happy to accept a PR, though.
